- hosts: init_master
  become: yes
  become_user: root
  gather_facts: yes
  
  tasks:
     - name: install Cert Manager
       shell: |
               helm repo add jetstack https://charts.jetstack.io
               helm repo update
               kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.crds.yaml
               helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.12.0 --set installCRDs=false --set 'extraArgs={--dns01-recursive-nameservers-only,--dns01-recursive-nameservers=8.8.8.8:53\,1.1.1.1:53}'
     - name: sleep 15 seconds
       ansible.builtin.pause:
         seconds: 15
     - name: copy Manifests
       copy:
        src: "{{ item.src }}" 
        dest: "{{ item.dest }}"
       with_items:  
        - { src: /root/manifests/cert-manager/clouddns-dns01-solver-svc-acct.yaml, dest: /root/clouddns-dns01-solver-svc-acct.yaml }
        - { src: /root/manifests/cert-manager/clusterissuer.yaml, dest: /root/clusterissuer.yaml }
        - { src: /root/manifests/cert-manager/letsencript.yaml,dest: /root/letsencript.yaml }

     - name: install clusterissuer
       shell: |
               kubectl apply -f /root/clouddns-dns01-solver-svc-acct.yaml
               kubectl apply -f /root/clusterissuer.yaml
               kubectl apply -f /root/letsencript.yaml
