- hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
    - name: preinstallation 
      apt:
        name: 
          - curl
          - wget
        state: present
    - name: install containerd
      shell: |
             sudo apt-get update
             sudo apt-get install -y ca-certificates curl gnupg apt-transport-https
             sudo install -m 0755 -d /etc/apt/keyrings
             curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
             sudo chmod a+r /etc/apt/keyrings/docker.gpg

              # Add the repository to Apt sources:
              echo \
                "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
                sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt update
              sudo apt install containerd -y
    - name: replace config
      shell: |     
             systemctl daemon-reload
             systemctl enable --now containerd
             mkdir -p /etc/containerd
             containerd config default > /etc/containerd/config.toml
             sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
             systemctl restart containerd
